version: 0.2

phases:
  install:
    commands:
      # - install terraform
      - "wget https://releases.hashicorp.com/terraform/0.15.2/terraform_0.15.2_linux_amd64.zip"
      - "unzip terraform_0.15.2_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
    - echo "........APPLYING PLAN FOR EC2 INSTANCES.........."
    - "make plan_ec2"
    - echo ".........APPLYING PLAN FOR DATABASE........."
    - "make plan_rds"
  build:
    commands:
    - "make apply_with_rds"

  post_build:
    commands:
    - echo "PIPELINE BUILD SUCCESS !!!"
